import React, { useState} from 'react';
import { useNavigate } from 'react-router-dom';

import { preview } from '../assets';  
import { FormField, Loader } from '../components';
import { getRandomPrompt} from '../utils';


const CreatePost = () => {
  const navigate = useNavigate();
  const [form, setform] = useState({
    name: '',
    prompt:'',
    photo: '',
  });


  const [generatingimage, setGeneratingImage] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleSubmit = () => {

  };

  const handleChange = (e) => {

  };

  const handleSupriseMe = () => {
    
  }


  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>
          Create
        </h1>
        <p className='mt-2 text-[#666e75] text-[14px] max-w[500px] '>
          Here you can create images that are generated by DALLE-AI        
        </p>
      </div>

      <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
          <FormField 
            LabelName = 'Your Name'
            type="text"
            name='name'
            placeHolder='John Doe'
            value={form.name}
            handleChang={handleChange}      
          />
           <FormField 
            LabelName = 'Prompt'
            type="text"
            name='prompt'
            placeHolder='panda mad scientist mixing sparkling chemicals, digital art'
            value={form.prompt}
            handleChang={handleChange}
            isSupriseMe
            handleSupriseMe={handleSupriseMe}      
          />
        </div>
      </form>

    </section>
  )
}

export default CreatePost